version: 0.1
Resources:
    - TargetService:
          Type: AWS::ECS::Service
          Properties:
              TaskDefinition: <TASK_DEFINITION>
              LoadBalancerInfo:
                  ContainerName: '20231214_01'
                  ContainerPort: 3000
